version: "3.1"
services:
  mockupdb:
    image: mysql:8.0.21      
    container_name: mockupdb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
    restart: always
    ports:
      - 3306:3306 
    environment:
      MYSQL_ROOT_PASSWORD: 'password' 
      MYSQL_DATABASE: 'mockup' 
    volumes:
      - ./data/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime
      - ./conf/init/:/docker-entrypoint-initdb.d/
    privileged: true 
    networks:
        mockup:
         ipv4_address: 177.6.0.11
        
  mockup:
    build:
      context: ../../src/server
      dockerfile: ./Dockerfile
    container_name: server
    restart: always
    volumes: 
      - ./data/uploads/:/opt/mockup/server/uploads/file
      - ./data/mockup/:/opt/mockup/server/uploads/mockup
    ports:
      - 8888:80
    depends_on:
      - mockupdb   
    networks:
        mockup:
          ipv4_address: 177.6.0.12
      
  # mockupnginx:
  #   image: nginx:latest
  #   container_name: mockupnginx
  #   ports:
  #     - 8880:80  # 暴露端口
  #   volumes: # 挂载
  #     - ./conf/web:/usr/share/nginx/html
  #     - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/localtime:/etc/localtime
  #   restart: always
  #   privileged: true 
  #   networks:
  #       mockup:
  #         ipv4_address: 177.6.0.13
      
      
networks:
  mockup:
    driver: bridge
    ipam:
      config:
        - subnet: '177.6.0.0/16'
